name: Update README.md

on:
  schedule:
    - cron: '*/1 * * * *'  # Run every minute
  workflow_dispatch:  # Allow manual trigger
  push:
    branches:
      - '*'  # Trigger when something is pushed to any branch
  pull_request:
    branches:
      - '*'  # Trigger when a pull request is created or updated

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Specify your Node.js version (e.g., 18)

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          npm install

      # Step 4: Run the update script to fetch data and update README.md
      - name: Run the update script
        run: |
          node updateReadme.js

      # Step 5: Commit and push the updated README.md file using a token
      - name: Commit and push updated README.md
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Updated README.md with dynamic stats"
          git push https://x-access-token:${{ secrets.ACTIONS_TOKEN }}@github.com/xnil6x404/xnil6x404.git HEAD:main
